apiVersion: v1
kind: Pod

metadata:
  name: nest-pod

spec:
  containers:
    - name: nest-container
      image: nest-server
      ports:
        - containerPort: 3000
      imagePullPolicy: IfNotPresent
