apiVersion: v1
kind: Pod

metadata:
  name: next-pod

spec:
  containers:
    - name: next-container
      image: next-server
      ports:
        - containerPort: 3000
      imagePullPolicy: IfNotPresent