apiVersion: v1
kind: Pod

metadata:
  name: static-web-server

spec:
  containers:
    - name: static-web-container
      image: static-web-server
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent