apiVersion: v1
kind: Service

metadata:
  name: spring-service

spec:
  type: NodePort
  selector:
    app: spring-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002