apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  type: NodePort
  selector:
    app: mysql-db

  ports:
    - protocol: TCP 
      port: 3306
      targetPort: 3306
      nodePort: 32206