apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pvc

spec:
  storageClassName: my-storage    # PV의 storageClassName과 일치해야 매칭됨
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
