apiVersion: v1
kind: PersistentVolume

metadata:
  name: mysql-pv  # PVC에서 이 이름을 직접 지정해서 바인딩하거나 storageClassName 기준으로 자동 연결

spec:
  storageClassName: my-storage    # 이 이름과 일치하는 PVC만 바인딩
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce               # 파드 접근 방식 제한: PV에 접근 가능한 모드
  hostPath:                       # hostPath는 노드의 로컬 디스크를 직접 사용하는 방식
    path: "/mnt/data"


## PersistentVolume
# - kubenetes에서 Pod의 데이터를 외부에 영속적으로 저장하기 위한 리소스
# - 로컬 디스크, NFS, 클라우드 디스크(EBS 등) 등 다양한 스토리지 사용 가능