apiVersion: v1
kind: Pod

metadata:
  name: spring-pod

spec:
  containers:
    - name: spring-container
      image: spring-server
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent


## ErrImagePull -> ImagePullBackOff 에러 발생
# 태그가 latest or 명시되지 않은 경우 => ImagePullPolicy가 Always로 설정 
# => 로컬이 아닌 레지스트리에서 이미지를 받아오려고 함
# => ImagePullPolicy를 직접 정의해 에러 해결

## --- Image Pull Policy ---
# 1. Always
#    - 항상 최신 이미지를 다시 다운로드
#    - 개발/테스트 환경이나 :latest 태그를 사용할 때 주로 사용
#    - 기본값: 태그가 'latest'이면 자동으로 Always로 설정
#
# 2. IfNotPresent
#    - 노드에 이미지가 없는 경우에만 다운로드
#    - 운영 환경에서 고정 버전(:v1.0.0 등)을 사용할 때 적합
#    - 기본값: 'latest'가 아닌 태그를 사용할 경우 자동으로 적용
#
# 3. Never
#    - 이미지를 절대 다운로드하지 않고, 노드에 있는 로컬 이미지만 사용
#    - 외부 레지스트리를 사용하지 않는 로컬 테스트용으로 적합
#    - 이미지가 없으면 오류가 발생하므로 주의가 필요