apiVersion: v1
kind: Pod

metadata:
  name: django-pod

spec:
  containers:
    - name: django-container
      image: django-server
      ports:
        - containerPort: 8000
      imagePullPolicy: IfNotPresent